enum ImageType {
  NONE, MY_PENDING, GOTOSTART,
  ARROW_N, ARROW_NNE, ARROW_NE, ARROW_ENE, ARROW_E, ARROW_ESE, ARROW_SE, ARROW_SSE,
  ARROW_S, ARROW_SSW, ARROW_SW, ARROW_WSW, ARROW_W, ARROW_WNW, ARROW_NW, ARROW_NNW,
  CHECKPOINT_1, CHECKPOINT_2, CHECKPOINT_3, CHECKPOINT_4, CHECKPOINT_5,
  CHECKPOINT_6, CHECKPOINT_7, CHECKPOINT_8, CHECKPOINT_9, CHECKPOINT_10
};

enum NavigationState {
  NOT_STARTED, NAVIGATING, AT_CHECKPOINT, TRAIL_ENDED
};
